### ISSUE TITLE
Add continuous integration

### ISSUE THREAD

**Issue by martintoreilly** [alan-turing-institute/science-gateway-cluster#2]
## Tasks
- [ ] Add tests for initial contents of repo
- [ ] Add `travis.yml` to trigger Travis CI build.
- [ ] Add`appveyor.yml` to trigger Appveyor CI build
- [ ] Restrict commits to master branch to require tests passing on Travis and Appveyor

**Comment by martintoreilly** [comment]
Some notes about testing Docker images - https://blog.jevsejev.io/2016/06/09/docker-image-tests/
